"""empty message

Revision ID: 13eb9aefbe60
Revises: 13d257d53a8e
Create Date: 2019-08-31 22:20:15.757000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eb9aefbe60'
down_revision = '13d257d53a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weiadmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weiadmin')),
    sa.UniqueConstraint('openid', name=op.f('uq_weiadmin_openid'))
    )
    op.drop_table('wei_admin')
    with op.batch_alter_table('weiitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weiadmin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_weiitem_weiadmin_id_weiadmin'), 'weiadmin', ['weiadmin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weiitem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_weiitem_weiadmin_id_weiadmin'), type_='foreignkey')
        batch_op.drop_column('weiadmin_id')

    op.create_table('wei_admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('openid', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_wei_admin'),
    sa.UniqueConstraint('openid', name='uq_wei_admin_openid')
    )
    op.drop_table('weiadmin')
    # ### end Alembic commands ###
