"""empty message

Revision ID: 2c33d1a94f16
Revises: 
Create Date: 2019-09-01 11:14:15.222000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c33d1a94f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paperday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paperdaycode', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paperday')),
    sa.UniqueConstraint('paperdaycode', name=op.f('uq_paperday_paperdaycode'))
    )
    op.create_table('weiadmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weiadmin')),
    sa.UniqueConstraint('openid', name=op.f('uq_weiadmin_openid'))
    )
    op.create_table('itembox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papercode', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('right', sa.String(), nullable=True),
    sa.Column('paperday_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paperday_id'], ['paperday.id'], name=op.f('fk_itembox_paperday_id_paperday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itembox'))
    )
    op.create_table('weiitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weiadmin_id', sa.Integer(), nullable=True),
    sa.Column('paperday_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paperday_id'], ['paperday.id'], name=op.f('fk_weiitem_paperday_id_paperday')),
    sa.ForeignKeyConstraint(['weiadmin_id'], ['weiadmin.id'], name=op.f('fk_weiitem_weiadmin_id_weiadmin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weiitem'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weiitem')
    op.drop_table('itembox')
    op.drop_table('weiadmin')
    op.drop_table('paperday')
    # ### end Alembic commands ###
