"""empty message

Revision ID: 7b36db338d89
Revises: bb8dad613b02
Create Date: 2019-09-01 15:56:50.958000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b36db338d89'
down_revision = 'bb8dad613b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weiadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ifstudent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weiadmin', schema=None) as batch_op:
        batch_op.drop_column('ifstudent')

    # ### end Alembic commands ###
