"""empty message

Revision ID: 93ea044dce56
Revises: 7b36db338d89
Create Date: 2019-09-01 17:57:44.871000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ea044dce56'
down_revision = '7b36db338d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itembox_id', sa.Integer(), nullable=True),
    sa.Column('right', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('weiitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itembox_id'], ['itembox.id'], name=op.f('fk_dati_itembox_id_itembox')),
    sa.ForeignKeyConstraint(['weiitem_id'], ['weiitem.id'], name=op.f('fk_dati_weiitem_id_weiitem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dati'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dati')
    # ### end Alembic commands ###
