"""0

Revision ID: a38fb288399c
Revises: 
Create Date: 2019-03-31 22:26:39.912130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38fb288399c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('secret', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_self_comment_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_self_comment'))
    )
    with op.batch_alter_table('self_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_self_comment_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_admin_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_admin_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_admin_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_admin_email'), type_='unique')

    with op.batch_alter_table('self_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_self_comment_timestamp'))

    op.drop_table('self_comment')
    # ### end Alembic commands ###
