"""empty message

Revision ID: c2b9a5e9c43b
Revises: 7941080af281
Create Date: 2019-08-31 10:14:20.126000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b9a5e9c43b'
down_revision = '7941080af281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itembox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papercode', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('right', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itembox'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itembox')
    # ### end Alembic commands ###
